<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugSymbols>False</DebugSymbols>
    <DebugType>None</DebugType>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <PublishDir>./bin/$(AssemblyName)/</PublishDir>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>2.1.6</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.375">
      <PrivateAssets>none</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentFTP" Version="53.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="lang\**\*.*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="payload.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
